name: Metrics

on:
  schedule: [{cron: "0 0 * * 0"}]  # roda todo domingo
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          user: eduardamoredias
          config_timezone: America/Sao_Paulo
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
